medics_academy/urls.py
from django.contrib import admin 
from django.urls import path,include 
from django.conf.urls.static import static
from django.conf import settings 
from courses.admin import medics_admin_site


from users.urls import urlpatterns as usersurl 
from django.conf.urls import include

from courses.views import MediaFileView
from users.views import ModuleMediaFileView,UserProfileViews

handler404 = 'courses.views.error_404_view'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', medics_admin_site.urls),
    path('', include("users.urls", namespace="user_app")), 
    # path('media/course_cover_images/<str:file_path>/', MediaFileView.course_media_view, name='course_media_view'), # type: ignore
    # path('<str:course_id>/media/modules_media/<str:file_path>/', ModuleMediaFileView.module_media_view, name='module_media_view'),
    #path('media/user_profile_images/<str:file_path>/', UserProfileViews.user_profile_media_view, name='user_profile_media_view'),
    #path('<str:course_id>/<str:media_id>/<str:signed_value>/', ModuleMediaFileView.module_media_signed_view, name='module_media_signed_view'),
    # path('payment/', include("payment.urls", namespace="payment_app")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from .views import initiate_payment, callback
from django.urls import path, register_converter

from . import converters

register_converter(converters.FloatUrlParameterConverter, 'float')

app_name = 'payment_app'

urlpatterns = [
    path('pay/<int:user_id>/<int:course_id>/', initiate_payment, name='pay'),
    path('callback/', callback, name='callback'),
]

users/urls.py
from django.urls import path, reverse_lazy
from django.conf import settings
from django.conf.urls import handler404 



from . import views 
from django.contrib.auth import views as auth # type: ignore
from django.contrib.auth import views as auth_views
from users.views import HomePageViews
app_name = 'user_app'

urlpatterns = [

     path("", views.HomePageViews.landing_page, name="landing_page"),
    

     path("login/", views.UserAuthendication.user_login, name="user_login"),
     path('activate/<uidb64>/<token>', views.UserAuthendication.activate, name='activate'),
   
     path("register/", views.UserAuthendication.register, name="userRegistration"),
     path("dashboard/",views.UserAuthendication.user_dash, name="user_dash"),
     path("dashboard_first/",views.UserAuthendication.user_dash_first, name="user_dash_first"),
     path("user_logout/",views.UserAuthendication.user_logout,name="user_logout"),
     path("user_profile_list/",views.UserProfileViews.user_general_view,name="user_profile_list"),
     path("user_courses/",views.Purchased.purchased_course,name="user_courses"),
     path("user_profile_edit/",views.UserProfileViews.user_edit_profile,name="user_profile_edit"),
      path("user_password_change_profile", views.UserProfileViews.user_password_change_profile,name="user_password_change_profile"),
     path("view_course/<int:pk>/", views.HomePageViews.course_detail, name="courseview"),
     # path("subscription_view/<int:pk>/",views.HomePageViews.offer_detail, name="subview"),
     # path("user_learn/<int:course_pk>/", views.HomePageViews.user_learn, name="userlearn"),
     path("module_assesment/<int:pk>/", views.HomePageViews.user_assesment,name="moduleasses"),
     path("payment/<int:pk>/", views.HomePageViews.course_payment, name="coursepayment"),
     path('add_to_saved/<int:user_id>/<int:course_id>/', views.SavedPage.add_to_saved, name='add_to_saved'),
     path('remove_from_saved/<int:user_id>/<int:course_id>/', views.SavedPage.remove_from_saved, name='remove_from_saved'),

     path('saved_page/', views.SavedPage.save_page, name='saved_page'),
     path('saved_check/<int:user_id>/<int:course_id>/', views.SavedPage.saved_check, name='saved_check'),
     path('search_course/',views.Search.search_courses,name='search'),
     path('about_us/',views.HomePageViews.about_us,name='about_us'),
     # path('contact_us/',views.HomePageViews.contact_us,name='contact_us'),
     path('contact_us_message/',views.HomePageViews.contact_us_message,name='contact_us_message'),
     path('reset_password/',auth_views.PasswordResetView.as_view(template_name="registration/reset_password.html",success_url=reverse_lazy('user_app:password_reset_done'), html_email_template_name='registration/password_reset_email.html'),name='password_reset'),
     path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
     path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('user_app:password_reset_complete')), name='password_reset_confirm'),

     path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='login.html'), name='password_reset_complete'),
     path('add_to_purchased/<int:user_id>/<int:course_id>/', views.Purchased.add_to_purchase, name='add_to_purchase'),
     path("user_learn/<int:course_pk>/", views.Purchased.learning, name="learning"),
     path("assessment_submit/", views.assessment_submit, name="assessment_submit"),

     # path("average_submit/<int:user_id>/<int:module_id>/",views.view_average_mark,name="assesment_mark"),

     # path("user_mt_token/", views.Purchased.set_material_token, name="material_token")
     path("get_popup_question/", views.Purchased.get_popup_question, name="get_popup_question"),
     path("store_course_progress/", views.Purchased.store_course_progress, name="store_course_progress"),


]


     # path("error/", views.error_page.error_404, name="error")
     

courses/models.py
from django.db import models # type: ignore
from django.core.validators import RegexValidator # type: ignore
from django.contrib.postgres.fields import ArrayField # type: ignore
from django.contrib.auth.models import User # type: ignore


# Create your models here.
class CourseModel(models.Model):
    FLAG1 = 'Trending'
    FLAG2 = 'Upselling'
    FLAGS = [
        (FLAG1, "Trending"),
        (FLAG2, "Upselling")
    ]
    course_title = models.CharField(max_length=255)
    total_modules = models.CharField(max_length=10,validators=[RegexValidator(regex="^[1-9][0-9]*$",message="Please enter only numbers")])
    version = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=15,decimal_places=2)
    cover_image = models.ImageField(upload_to="course_cover_images/", max_length=255)
    course_author = models.CharField(max_length=255, null=True, blank=False)
    course_expertise = models.TextField(null=True, blank=False)
    flag = ArrayField(models.CharField(max_length=100, choices=FLAGS),null=True, blank=True)
    status = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ModuleModel(models.Model):
    OPTION1 = 'Audio'
    OPTION2 = 'Video'
    OPTION3 = 'Document'

    MODULE_TYPES = [
        (OPTION1, "Audio"),
        (OPTION2, "Video"),
        (OPTION3, "Document")
    ]

    course = models.ForeignKey(CourseModel, on_delete=models.PROTECT)
    module_title = models.CharField(max_length=255)
    material_title = models.CharField(max_length=255, null=True, blank=False)
    order = models.CharField(max_length=255, validators=[RegexValidator(regex="^[1-9][0-9]*$",message="Please enter only numbers")])
    
    duration_days = models.CharField(max_length=10)
    duration_months = models.CharField(max_length=10)
    module_type = ArrayField(models.CharField(max_length=100, choices=MODULE_TYPES),default=None)
    status = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ModulesMediaFile(models.Model):
    module = models.ForeignKey(ModuleModel, on_delete=models.CASCADE)
    uploaded_file = models.FileField(upload_to="modules_media/", null=True, blank=True)
    link= models.TextField(null=True, blank=True)
    file_type = models.CharField(max_length=50, null=True, blank=True)
    file_extension = models.CharField(max_length=50, null=True, blank=True)
    order = models.CharField(max_length=50, null=True, blank=True, validators=[RegexValidator(regex="^[0-9]*(\.[0-9]{1,2})?$",message="Please enter only numbers or decimals")])
    created_at = models.DateTimeField(auto_now_add=True)

class Question(models.Model):
    module = models.ForeignKey(ModuleModel, on_delete=models.CASCADE)
    question_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField()
    is_correct_answer = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class PopupQuestion(models.Model):
    popup_show_time = models.CharField(max_length=255, null=True, blank=True)
    module = models.ForeignKey(ModuleModel, on_delete=models.CASCADE)
    popup_question_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class PopupChoice(models.Model):
    popup_question = models.ForeignKey(PopupQuestion, on_delete=models.CASCADE)
    popup_choice_text = models.TextField()
    is_correct_answer = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Subscription(models.Model):
    course = models.ForeignKey(CourseModel, on_delete=models.CASCADE)
    user = models.ManyToManyField(User)
    price = models.DecimalField(max_digits=15,decimal_places=2)
    discount = models.DecimalField(max_digits=15,decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from .custom_module import phone_number_validator
from django.contrib.auth.forms import PasswordResetForm

class RegistrationForm(forms.Form):

    GENDER = [
        ("F", "Female"),
        ("M", "Male"),
    ]
   
    phone_number = forms.CharField(
        required=True,
        error_messages={'required': 'Phone number is required'},
        validators=[phone_number_validator]
    )

    name = forms.CharField(required = True, error_messages={'required': 'Please enter your name'})
    gender = forms.ChoiceField(required = True, error_messages={'required': 'Please enter your gender'}, choices=GENDER)
    email = forms.EmailField(required = True,validators=[validators.validate_email],error_messages={'required': 'Please enter your email'})
    # country_code = forms.CharField(required = True)

    # def clean(self):
    #     cleaned_data = super().clean()
    #     email = cleaned_data.get('email')
    #     if(User.objects.filter(email=email).exists()):
    #         self.add_error('email', 'Email Already exists!')
    #     return cleaned_data

class RegistrationForm1(forms.Form):
    OCCUPATION = [
        ("S", "Student"),
        ("T", "Teacher"),
        ("O", "Others")
    ]
    occupation = forms.ChoiceField(required=True, error_messages={'required': 'Please enter your occupation'}, choices=OCCUPATION)
    occupation_others = forms.CharField(required=False)
    college = forms.CharField(required=False)
    password = forms.CharField(required=True, error_messages={'required': 'Please enter the password'})
    confirm_password = forms.CharField(required=True, error_messages={'required': 'Please confirm the password'})
    termcheck = forms.BooleanField(required=True)

    def is_valid_password(self, password):
        if len(password) < 8:
            return False

        has_capital = False
        has_number = False
        has_special = False

        for char in password:
            if char.isupper():
                has_capital = True
            elif char.isnumeric():
                has_number = True
            elif char in "!@#$%^&*()_+{}|:\"<>?":
                has_special = True

        return has_capital and has_number and has_special

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not self.is_valid_password(password):
            raise forms.ValidationError("Password must be at least 8 characters long and contain at least one capital letter, one number, and one special character.")
        return password

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        select_occupation = cleaned_data.get('occupation')
        other_occupation = cleaned_data.get('occupation_others')
        college = cleaned_data.get('college')

        if select_occupation == "S" and college == '':
            self.add_error('college', 'Please enter your college')
        if select_occupation == "O" and other_occupation == '':
            self.add_error('occupation_others', 'Please enter your other occupation')
        if password != confirm_password:
            self.add_error('password', 'Password does not match')

        return cleaned_data

class UserProfileEdit(forms.Form):

    email = forms.EmailField(required = True,validators=[validators.validate_email],error_messages={'required': 'Please enter your email'})
    first_name = forms.CharField(required = True, error_messages={'required': 'Please enter your first name'})
    last_name = forms.CharField(required = True, error_messages={'required': 'Please enter your last name'})
    profile_img = forms.ImageField(required=True, error_messages={'required': 'Please choose your photo'})


class UserProfileChangePassword(forms.Form):

    old_password = forms.CharField(required = True)
    new_password1 = forms.CharField(required = True)
    new_password2 = forms.CharField(required = True)
   
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('new_password1')
        confirm_password = cleaned_data.get('new_password2')

        if(password != confirm_password):
            self.add_error('new_password2', 'Password does not match')
        return cleaned_data



# class CustomPasswordResetForm(PasswordResetForm,RegistrationForm1):
#     email = forms.EmailField(
#         label="Email",
#         max_length=254,
#         widget=forms.EmailInput(attrs={'class': 'form-control'}),
#     )

#     def clean_email(self):
#         email = self.cleaned_data.get('email')
#         if not User.objects.filter(email=email).exists():
#             raise forms.ValidationError("This email address is not associated with any account.")
#         return email

#     def clean_password(self):
#         password = self.cleaned_data.get('password')
#         if not self.is_valid_password(password):
#             raise forms.ValidationError("Password must be at least 8 characters long and contain at least one capital letter, one number, and one special character.")
#         return password

users/templates/payment_details.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
Assessement
{% endblock %}
{% block styles %}


<link rel="stylesheet" href="{% static 'css/user/user_user_style.css' %}">
<link rel="stylesheet" href="{% static 'css/user/mobile_view.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block content %}
<div class="container-fluid header border_line">
    <div class="container">

      
    </div>
</div>
<!-- content -->
<div class="section">
    <div class="container">

        <nav class="navbar navbar-expand-lg ">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="#"><img src="{% static 'images/user/home.png' %}"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url 'user_app:user_dash' %}">Course</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_app:courseview' course.pk %}">Course Detail</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Payment</a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="row">

            <div class="col-lg-8">
                <h3>Payment</h3>
                <div class="card card-body rounded-4  p-3">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-inline mb-3">
                                <label>Select Payment Type</label><br>
                                    <select class="form-control" id="inputGroupSelect01" >
                                        <option selected>Single Payment</option>
                                        <option value="1">One</option>
                                        <option value="2">Two</option>
                                        <option value="3">Three</option>
                                    </select>
                            </div>
                        </div>
                        <div class="row">
                            <form method="post" action="pay/"> {% csrf_token %}
                            <!-- <div class="col-lg-2">
                                <div class="card px-2 pt-2 pb-2">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="exampleRadios"
                                            id="exampleRadios1" value="option1" checked>
                                        <label class="form-check-label" for="exampleRadios1">
                                            <img src="{%static 'images/user/card.png' %}" class="px-1">Card
                                        </label>
                                    </div>
                                </div>
                            </div> -->
                            <!-- <div class="col-lg-2">
                                <div class="card px-2 pt-2 pb-2">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="exampleRadios"
                                            id="exampleRadios1" value="option1" checked>
                                        <label class="form-check-label" for="exampleRadios1">
                                            <img src="{%static 'images/user/gpay.png' %}" class="px-1">
                                        </label>
                                    </div>
                                </div>
                            </div> -->

                            <!-- <div class="col-lg-2">
                                <div class="card px-1 pt-2 pb-2 ">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="exampleRadios"
                                            id="exampleRadios1" value="option1" checked>
                                        <label class="form-check-label" for="exampleRadios1">
                                            <img src="{%static 'images/user/phone_pe.png' %}" class="px-1">
                                        </label>
                                    </div>
                                </div>
                            </div> -->

                            <div class="col-lg-2">
                                <div class="card px-2 pt-2 pb-2">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="exampleRadios"
                                            id="exampleRadios1" value="option1" checked>
                                        <label class="form-check-label" for="exampleRadios1">
                                            <img src="{%static 'images/user/paytm.png' %}" class="px-1">
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- <h3 class="mt-3">Card Details</h3> -->
                    <div class="col-lg-9">
                        <!-- <label>Card Number</label>
                        <div class="input-group">
                            <br>

                            <input type="text" class="form-control"
                                aria-label="Dollar amount (with dot and two decimal places)"
                                placeholder="0000-0000-0000-0000">
                            <span class="input-group-text"><img src="{%static 'images/user/Card2.png' %}"></span>
                        </div>
                        <label class="mt-3">CVV</label>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                aria-label="Dollar amount (with dot and two decimal places)" placeholder="Enter CVV">
                            <span class="input-group-text"><img src="{%static 'images/user/eye.png' %}"></span>
                        </div>

                        <label class="mt-3">Card Holder Name</label>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Enter Name">

                        </div> -->
                        {% if user.is_authenticated %}
                        <a href="{% url 'payment_app:pay' user.id course.id  %}" class="btn btn-pay mt-4 p-3 px-5">Pay Now</a>
                        <a href="{% url 'user_app:add_to_purchase' user.id course.id  %}" class="btn btn-pay mt-4 p-3 px-5">Purchase Demo</a>
{% endif %}

                    </div>




                </div>
                <div class="col-lg-1">
                    <a href="{% url 'user_app:courseview' course.pk %}"><img src="{%static 'images/user/back.png' %}"></a>
                </div>



            </div>
            <div class="col-lg-4">
                <h3>Payment Summary</h3>
                <div class="card card-body rounded-4  p-3 ">
                    <div class="row pb-3 pt-3">
                        <div class="col-lg-9">Course Fee</div>
                        <div class="col-lg-3">{{course.price}}</div>
                    </div>
                    <div class="row pb-3">
                        <div class="col-lg-9">Tax</div>
                        <div class="col-lg-3">₹ 0</div>
                    </div>
                    <div class="row pb-3">
                        <!-- <div class="col-lg-12"><img src="{%static 'images/user/line.png' %}"></div> -->
                        <div class="line"></div>
                    </div>
                    <div class="row pb-3">
                        <div class="col-lg-9">Total</div>
                        <div class="col-lg-3">₹ 0</div>
                    </div>
                </div>
            </div>




        </form>
        </div>


        {% endblock %}

        <!-- footer -->

users/templates/user_custom_footer.html
<footer class="bg-dark text-white text-center mt-auto  py-3 fixed-bottom mt-5 custom-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>&copy; 2023 All rights reserved. <span style="color: #3ca0ba;">Medics Academy</span></p>

        </div>
      </div>
    </div>
  </footer>

users/templates/user_search.html
{% extends "user_base.html" %}
{% load static %}

{% block title %}
Search
{% endblock %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/user/user_home_page.css' %}">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<!-- <link rel="stylesheet" href="{% static 'css/user/fontawesome.css' %}"> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}





{% block content %}
{% if not user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
        <a class="navbar-brand" href="{% url 'user_app:user_dash' %}">
            <img src="/static/images/user/form-logo.svg" alt="Logo" width="116" height="48"
                class="d-inline-block align-text-top">
        </a>
        <div class="hhh">
            <ul class="navbar-nav ">
                <li class="nav-item">
                    <!-- <a class="nav-link btn btn-light px-2" aria-current="page" href="#">My Learnings</a> -->
                </li>
        </div>
        <div class="form-group has-search px-4">
            <span class="fa fa-search form-control-feedback form-control-feedback-custom"></span>
            <form method="POST" action="{% url 'user_app:search' %}">
                {% csrf_token %}
                <input type="text" class="form-control nav-form-control" placeholder="Search For classes, skills, courses..." name="searched">
            </form>
        </div>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item px-4">
                    <a class="nav-link active" aria-current="page" href="{% url 'user_app:user_dash' %}">Home</a>
                    <!-- <button type="button btn-text" class="btn btn-light">Home</button> -->
                </li>
                <li class="nav-item px-3">
                    <a class="nav-link t" href="{% url 'user_app:about_us' %}">About Us</a>
                    <!-- <button type="button btn-text" class="btn btn-light">About Us</button> -->
                </li>
                <!-- <li class="nav-item px-3">
                    <a class="nav-link " href="{#% url 'user_app:contact_us' %#}">Contact Us</a> -->
                    <!-- <button type="button btn-text" class="btn btn-light">Contact Us</button> -->
                <!-- </li> -->


                <li class="nav-item">
                    <a class="navbar-brand" href="{% url 'user_app:user_profile_list' %}">
                        <img src="/static/images/user/profile_pic.png" class="rounded-circle" alt="Profile Pic" width="48"
                            height="48">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% endif %}













<div class="container mt-5">

{% if searched %}
  <div class="row mt-5">
            <div class="col-12">
                <div class="d-flex justify-content-between">
                    <p class= "h5 trending-title">You Searched For {{searched}}</p>
                    {% if not user.is_authenticated %}
    <a class="title-more" href="{% url 'user_app:landing_page' %}">< Back</a>
{% endif %}

                </div>
            </div>
        </div>

{% for c in courses %}
  {% if c.status == True %}
<div class="card rounded-3 p-2 mt-3">
  <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-12 ">
          <div class="row">
              <div class="d-flex align-items-center">
                  <img src="{{c.cover_image.url}}" class="img-fluid" alt="{{c.course_title}}" width="110" height="110">
                  <div class="p-1 ms-2">
                      <h6 class="heading">{{c.course_title}}</h6>
                      <p class="contents">Jemin Mathew</p>
                  </div>
              </div>
          </div>
      </div>
      <div class="col-lg-8 col-md-6 col-sm-12">
          <div class="row align-items-center">
              <div class="col-4 col-md-3 mt-3">
                  <div class="p-1">
                      <h6 class="heading">Modules</h6>
                      <div class="d-flex card-text">
                          <p class="m-0"></p>
                          <i class="ms-1"></i>
                          <p class="ms-1">{{c.modulemodel_set.count}}</p>
                      </div>
                  </div>
              </div>
              <div class="col-4 col-md-3 ">
                  <div class="p-1">
                      <h6 class="heading">Duration</h6>
                      <div class="d-flex card-text">
                          <i class="bi bi-clock-fill card-text-star "></i>
                          <p class="m-0 ms-2 card-text">3h <span>45min</span></p>
                      </div>
                  </div>
              </div>
              <div class="col-4 col-md-3 mt-3">
                  <div class="p-1">
                      <h6 class="heading">Price</h6>
                      <div class="d-flex card-text">
                          <p class="h6 price">₹ {{c.price}}</p>
                          <p class="ms-1"><sub><s></s></sub></p>
                      </div>
                  </div>
              </div>
              <div class="col-12 col-md-3 mt-3">
                  <div class="p-1">
                      <a href="{% url 'user_app:courseview' pk=c.pk %}" class="btn btn-custom-brand">Enroll Now</a>

                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
{% endif %}
{% endfor %}
{% else %}
   <h5>You Forgot To Search For A Course</h5>
{% endif %}



</div>

{% if not user.is_authenticated %}
<footer class="bg-dark text-white text-center mt-auto  py-3 fixed-bottom mt-5 custom-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>&copy; 2023 All rights reserved. <span style="color: #3ca0ba;">Medics Academy</span></p>

        </div>
      </div>
    </div>
  </footer>
  {% endif %}



{% endblock %}