medics_academy/urls.py
from django.contrib import admin 
from django.urls import path,include 
from django.conf.urls.static import static
from django.conf import settings 
from courses.admin import medics_admin_site


from users.urls import urlpatterns as usersurl 
from django.conf.urls import include

from courses.views import MediaFileView
from users.views import ModuleMediaFileView,UserProfileViews

handler404 = 'courses.views.error_404_view'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', medics_admin_site.urls),
    path('', include("users.urls", namespace="user_app")), 
    # path('media/course_cover_images/<str:file_path>/', MediaFileView.course_media_view, name='course_media_view'), # type: ignore
    # path('<str:course_id>/media/modules_media/<str:file_path>/', ModuleMediaFileView.module_media_view, name='module_media_view'),
    #path('media/user_profile_images/<str:file_path>/', UserProfileViews.user_profile_media_view, name='user_profile_media_view'),
    #path('<str:course_id>/<str:media_id>/<str:signed_value>/', ModuleMediaFileView.module_media_signed_view, name='module_media_signed_view'),
    # path('payment/', include("payment.urls", namespace="payment_app")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from django.conf import settings
from django.conf.urls import handler404 



from . import views 
from django.contrib.auth import views as auth # type: ignore
from django.contrib.auth import views as auth_views
from users.views import HomePageViews
app_name = 'user_app'

urlpatterns = [

     path("", views.HomePageViews.landing_page, name="landing_page"),
    

     path("login/", views.UserAuthendication.user_login, name="user_login"),
     path('activate/<uidb64>/<token>', views.UserAuthendication.activate, name='activate'),
   
     path("register/", views.UserAuthendication.register, name="userRegistration"),
     path("dashboard/",views.UserAuthendication.user_dash, name="user_dash"),
     path("dashboard_first/",views.UserAuthendication.user_dash_first, name="user_dash_first"),
     path("user_logout/",views.UserAuthendication.user_logout,name="user_logout"),
     path("user_profile_list/",views.UserProfileViews.user_general_view,name="user_profile_list"),
     path("user_courses/",views.Purchased.purchased_course,name="user_courses"),
     path("user_profile_edit/",views.UserProfileViews.user_edit_profile,name="user_profile_edit"),
      path("user_password_change_profile", views.UserProfileViews.user_password_change_profile,name="user_password_change_profile"),
     path("view_course/<int:pk>/", views.HomePageViews.course_detail, name="courseview"),
     # path("subscription_view/<int:pk>/",views.HomePageViews.offer_detail, name="subview"),
     # path("user_learn/<int:course_pk>/", views.HomePageViews.user_learn, name="userlearn"),
     path("module_assesment/<int:pk>/", views.HomePageViews.user_assesment,name="moduleasses"),
     path("payment/<int:pk>/", views.HomePageViews.course_payment, name="coursepayment"),
     path('add_to_saved/<int:user_id>/<int:course_id>/', views.SavedPage.add_to_saved, name='add_to_saved'),
     path('remove_from_saved/<int:user_id>/<int:course_id>/', views.SavedPage.remove_from_saved, name='remove_from_saved'),

     path('saved_page/', views.SavedPage.save_page, name='saved_page'),
     path('saved_check/<int:user_id>/<int:course_id>/', views.SavedPage.saved_check, name='saved_check'),
     path('search_course/',views.Search.search_courses,name='search'),
     path('about_us/',views.HomePageViews.about_us,name='about_us'),
     # path('contact_us/',views.HomePageViews.contact_us,name='contact_us'),
     path('contact_us_message/',views.HomePageViews.contact_us_message,name='contact_us_message'),
     path('reset_password/',auth_views.PasswordResetView.as_view(template_name="registration/reset_password.html",success_url=reverse_lazy('user_app:password_reset_done'), html_email_template_name='registration/password_reset_email.html'),name='password_reset'),
     path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
     path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('user_app:password_reset_complete')), name='password_reset_confirm'),

     path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='login.html'), name='password_reset_complete'),
     path('add_to_purchased/<int:user_id>/<int:course_id>/', views.Purchased.add_to_purchase, name='add_to_purchase'),
     path("user_learn/<int:course_pk>/", views.Purchased.learning, name="learning"),
     path("assessment_submit/", views.assessment_submit, name="assessment_submit"),

     # path("average_submit/<int:user_id>/<int:module_id>/",views.view_average_mark,name="assesment_mark"),

     # path("user_mt_token/", views.Purchased.set_material_token, name="material_token")
     path("get_popup_question/", views.Purchased.get_popup_question, name="get_popup_question"),
     path("store_course_progress/", views.Purchased.store_course_progress, name="store_course_progress"),


]


     # path("error/", views.error_page.error_404, name="error")
     

courses/models.py
from django.db import models # type: ignore
from django.core.validators import RegexValidator # type: ignore
from django.contrib.postgres.fields import ArrayField # type: ignore
from django.contrib.auth.models import User # type: ignore


# Create your models here.
class CourseModel(models.Model):
    FLAG1 = 'Trending'
    FLAG2 = 'Upselling'
    FLAGS = [
        (FLAG1, "Trending"),
        (FLAG2, "Upselling")
    ]
    course_title = models.CharField(max_length=255)
    total_modules = models.CharField(max_length=10,validators=[RegexValidator(regex="^[1-9][0-9]*$",message="Please enter only numbers")])
    version = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=15,decimal_places=2)
    cover_image = models.ImageField(upload_to="course_cover_images/", max_length=255)
    course_author = models.CharField(max_length=255, null=True, blank=False)
    course_expertise = models.TextField(null=True, blank=False)
    flag = ArrayField(models.CharField(max_length=100, choices=FLAGS),null=True, blank=True)
    status = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ModuleModel(models.Model):
    OPTION1 = 'Audio'
    OPTION2 = 'Video'
    OPTION3 = 'Document'

    MODULE_TYPES = [
        (OPTION1, "Audio"),
        (OPTION2, "Video"),
        (OPTION3, "Document")
    ]

    course = models.ForeignKey(CourseModel, on_delete=models.PROTECT)
    module_title = models.CharField(max_length=255)
    material_title = models.CharField(max_length=255, null=True, blank=False)
    order = models.CharField(max_length=255, validators=[RegexValidator(regex="^[1-9][0-9]*$",message="Please enter only numbers")])
    
    duration_days = models.CharField(max_length=10)
    duration_months = models.CharField(max_length=10)
    module_type = ArrayField(models.CharField(max_length=100, choices=MODULE_TYPES),default=None)
    status = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ModulesMediaFile(models.Model):
    module = models.ForeignKey(ModuleModel, on_delete=models.CASCADE)
    uploaded_file = models.FileField(upload_to="modules_media/", null=True, blank=True)
    link= models.TextField(null=True, blank=True)
    file_type = models.CharField(max_length=50, null=True, blank=True)
    file_extension = models.CharField(max_length=50, null=True, blank=True)
    order = models.CharField(max_length=50, null=True, blank=True, validators=[RegexValidator(regex="^[0-9]*(\.[0-9]{1,2})?$",message="Please enter only numbers or decimals")])
    created_at = models.DateTimeField(auto_now_add=True)

class Question(models.Model):
    module = models.ForeignKey(ModuleModel, on_delete=models.CASCADE)
    question_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField()
    is_correct_answer = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class PopupQuestion(models.Model):
    popup_show_time = models.CharField(max_length=255, null=True, blank=True)
    module = models.ForeignKey(ModuleModel, on_delete=models.CASCADE)
    popup_question_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class PopupChoice(models.Model):
    popup_question = models.ForeignKey(PopupQuestion, on_delete=models.CASCADE)
    popup_choice_text = models.TextField()
    is_correct_answer = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Subscription(models.Model):
    course = models.ForeignKey(CourseModel, on_delete=models.CASCADE)
    user = models.ManyToManyField(User)
    price = models.DecimalField(max_digits=15,decimal_places=2)
    discount = models.DecimalField(max_digits=15,decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

users/models.py
from django.db import models




from django.contrib.auth.models import User
from courses .models import CourseModel ,ModuleModel,Question,Choice, ModulesMediaFile

from payment .models import Payment

# Create your models here.
class UserProfileModel(models.Model):
    GENDER_CHOICES = [
        ('F', 'Female'),
        ('M', 'Male'),
        ('O', 'Others'),
    ]

    OCCUPATION = [
        ("S", "Student"),
        ("T", "Teacher"),
        ("O", "Others")
    ]



    user = models.ForeignKey(User, on_delete=models.CASCADE)
    country_code = models.CharField(max_length=10, default=None)
    phone_number = models.CharField(max_length=10)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    occupation = models.CharField(max_length=1, choices=OCCUPATION)
    occupation_others = models.CharField(max_length=255, blank=True)
    college = models.CharField(max_length=255, blank=True)
    profile_img = models.ImageField(upload_to='user_profile_images/', null=True)





class SavedCourses(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(CourseModel, on_delete=models.CASCADE)


class PurchasedCourse(models.Model):
    users = models.ForeignKey(User, on_delete=models.CASCADE)
    courses = models.ForeignKey(CourseModel , on_delete=models.CASCADE)
    purchase_date = models.DateTimeField(auto_now_add=True)







class AttemptedAssessment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    module = models.ForeignKey(ModuleModel,on_delete=models.CASCADE)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    selected_choice = models.ForeignKey(Choice,on_delete=models.CASCADE)
    assessment_date = models.DateField(auto_now_add=True)
    is_correct = models.BooleanField(default=False)

class CourseProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(CourseModel , on_delete=models.CASCADE)
    module = models.ForeignKey(ModuleModel,on_delete=models.CASCADE)
    modulemediafile = models.ForeignKey(ModulesMediaFile, on_delete=models.CASCADE)
    watched_date = models.DateTimeField(auto_now_add=True)






class ReAssessment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    module = models.ForeignKey(ModuleModel,on_delete=models.CASCADE)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    selected_choice = models.ForeignKey(Choice,on_delete=models.CASCADE)
    assessment_date = models.DateField(auto_now_add=True)
    is_correct = models.BooleanField(default=False)



class ReAssessmentAverage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(CourseModel , on_delete=models.CASCADE)
    module = models.ForeignKey(ModuleModel,on_delete=models.CASCADE)
    reassessment_date = models.DateField(auto_now_add=True)
    average = models.DecimalField(max_digits=10, decimal_places=2)

users/templates/profile/user_my_courses.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
{{user.username}} Courses
{% endblock %}
{% block styles %}
{% load custom_filters %}

<link rel="stylesheet" href="{% static 'css/user/user_user_style.css' %}">
<link rel="stylesheet" href="{% static 'css/user/mobile_view.css' %}">


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}
{% block content %}
<div class="container">
    <div class="row p-3  mb_p">
        <!-- <div class="col-xl-1 col-3">
            <a href=""><img src="{% static 'images/user/back-arrow.png' %}"></a>
        </div> -->
        <div class="col-xl-12 col-12">
            <h4><span class="page_title ms-2">Profile</span></h4>
        </div>
    </div>
    <div class="row p-3 ">
        <div class="col-md-3">
            {% include "profile/user_profile_sidebar.html" with active="user_courses" %}
        </div>
        <div class="col-md-9 pb-5">
          
            <div class="card card-body rounded-4  p-3">
                
                {% for course in purchased_course_models %}
               
                <!-- <h5 class="text-center">"You have not yet purchased any courses."</h5> -->
                <div class="card card-body card-border rounded-4 mt-2 p-3">
            
                    <div class="row pt-3">
                        <div class="col-lg-2 col-sm-4">
                            <img src="{{ course.cover_image.url }}" height="100" width="100">
                        </div>
                        <div class="col-lg-10 col-sm-8s mt-3">
                            <h3>{{ course.course_title }}</h3>
                            <h5>{{ course.course_author }}</h5>

                            <div class="row">
                                <div class="col-lg-3">
                                    <p>Duration</p>
                                    <h6><img class="me-1" src="{% static 'images/user/duration.png' %}">{{ course.course_duration_months }} Months {{ course.course_duration_days }} Days </h6>
                                </div>
                                <!-- <div class="col-lg-3">
                                    <p>Ratings</p>
                                    <h6>4.0<img src="{% static 'images/user/star.png' %}"  class="px-1">(36 Reviews)</h6>
                                </div> -->
                                <div class="col-lg-3">
                                    <p>Modules</p>
                                    <h6>{{course.modulemodel_set.count}} Modules</h6>
                                </div>
                                <div class="col-lg-3">
                                    <p>Version</p>
                                    <h6>{{course.version}}</h6>
                                </div>
                                <div class="col-lg-3">
                                    <p>Assessment Score </p>
                                    <h6>1.1</h6>
                                </div>
                            </div>

                            <div class="row mt-4">
                                <div class="col-lg-3">
                                    <a href="{% url 'user_app:learning' course.pk %}" class="btn btn-color mb_text">Start Learning</a> 

                                </div>
                                {% with user|purchased_course_progress_percentage:course as progress %}
                                <div class="col-lg-6">
                                    <div class="progress mb_text">
                                        <div class="progress-bar custom-progress " role="progressbar" style="width: {{progress}}%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                                            {{progress}}%
                                        </div>
                                    </div>

                                </div>
                                {% endwith %}
                                <div class="col-lg-3">
                                    <button type="button" class="btn  btn-outline-success text-success mb_text">Payment - <span>Done</span></button>
                                    
                                </div>
                            </div>




                        </div>

                    </div>
                 
                </div> 
                {% endfor %}
 </div>
                <!-- <div class="card card-body card-border rounded-4  p-3 mt-3">
                    
                    <div class="row pt-3">
                        <div class="col-lg-2 col-sm-4">
                            <img src="{% static 'images/user/my_course.png' %}">
                        </div>
                        <div class="col-lg-10 col-sm-8s mt-3">
                            <h3>Course Name In 2 to 3lines Study material</h3>
                            <h5>Jayamravi Rajamovli</h5>

                            <div class="row">
                                <div class="col-lg-2">
                                    <p>Duration</p>
                                    <h6><img src="{% static 'images/user/duration.png' %}">36h 45min</h6>
                                </div>
                                <div class="col-lg-3">
                                    <p>Ratings</p>
                                    <h6>4.0<img src="{% static 'images/user/star.png' %}"  class="px-1">(36 Reviews)</h6>
                                </div>
                                <div class="col-lg-2">
                                    <p>Modules</p>
                                    <h6>11 Modules</h6>
                                </div>
                                <div class="col-lg-2">
                                    <p>Version</p>
                                    <h6>1.1</h6>
                                </div>
                                <div class="col-lg-3">
                                    <p>Assessment Score </p>
                                    <h6>1.1</h6>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-lg-4">
                                    <button type="button" class="btn btn-color mb_text">Start Learning</button>

                                </div>
                                <div class="col-lg-4 pt-2">
                                    <div class="progress">
                                        <div class="progress-bar custom-progress " role="progressbar" style="width: 70%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                                            70%
                                        </div>
                                    </div>

                                </div>
                                <div class="col-lg-4">
                                    <button type="button" class="btn btn-color payment-btn px-4">Payment - <span>Done</span></button>
                                    
                                </div>
                            </div>




                        </div>

                    </div>

                  
                    <!-- </div> -->

<!-- 
                </div> --> 


            
            
           
        </div>
    </div>
</div>
{% endblock %}

users/templates/profile/user_profile_change_password.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
User Profile
{% endblock %}
{% block styles %}

<link rel="stylesheet" href="{% static 'css/user/user_user_style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}
{% block content %}
<div class="container">
    <div class="row p-3 ">
        <!-- <div class="col-1">
            <a href=""><img src="{% static 'images/user/back-arrow.png' %}"></a>
        </div> -->
        <div class="col-12">
            <h4><span class="page_title ms-2">Profile</span></h4>
        </div>
    </div>
    <div class="row p-3 ">
        <div class="col-md-3">
            {% include "profile/user_profile_sidebar.html" with active="profile_change_password" %}
        </div>
        <div class="col-md-9">
            <div class="card card-body">

                <h3>Change Password</h3>

                <form  method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-9">
                            <label for="oldPassword" class="form-label">Old Password</label>
                            <input type="password" class="form-control" placeholder="Enter Old Password"
                                id="oldPassword" name="old_password">
                            {% if form.old_password %}
                                <span class="text-danger error-message">{{form.old_password.0}}<br></span>
                            {% endif %}
                            <br>

                            <label for="newPassword" class="form-label">New Password</label>
                            <input type="password" class="form-control" placeholder="Enter New Password"
                                id="newPassword" name="new_password1">
                            {% if form.new_password1 %}
                                <span class="text-danger error-message">{{form.new_password1.0}}<br></span>
                            {% endif %}
                            <br>

                            <label for="confirmPassword" class="form-label">Confirm Password</label>
                            <input type="password" class="form-control" placeholder="Enter Confirm Password"
                                id="confirmPassword" name="new_password2">
                            {% if form.new_password2 %}
                                <span class="text-danger error-message">{{form.new_password2.0}}<br></span>
                            {% endif %}
                            <br>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12">
            <div class="d-flex justify-content-end me-3">

                <button type="button" class="btn btn-outline-dark me-3 px-4">Close</button>
                <button type="submit" class="btn btn-dark  px-4">Save</button>

            </div>
        </div>
    </div>
</form>
</div>
{% endblock %}
{% block scripts %}
<script>
    $(function(){
        $('.form-control').on('keypress', function(){
                $(this).next('.error-message').remove();
        });
    });
</script>
{% endblock %}

users/templates/profile/user_profile_general.html
{% extends "user_base.html" %}
{% load static %}
{% block title %}
User Profile
{% endblock %}
{% block styles %}


<link rel="stylesheet" href="{% static 'css/user/user_user_style.css' %}">
<link rel="stylesheet" href="{% static 'css/user/mobile_view.css' %}">
<style>
    .custom-cards{
        border: unset !important;
        background-color: #ebf5f8;
    }
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  
{% endblock %}
{% block content %}
<div class="container">
    <div class="row p-3  mb_p">
        <div class="col-xl-1 col-3">
            <a href="{% url 'user_app:user_dash' %}"><img src="{% static 'images/user/back-arrow.png' %}"></a>
        </div>
        <div class="col-xl-11 col-9">
            <h4><span class="page_title">Profile</span></h4>
        </div>
    </div>
    <div class="row p-3 ">
        <div class="col-md-3">
            {% include "profile/user_profile_sidebar.html" with active="general" %}
        </div>
        <div class="col-md-9 pb-5">

            <div class="card p-5 card-body">


                <div class="row">
                    {% if user.is_authenticated %}
                    {% for u in user.userprofilemodel_set.all %}
                        

                    <div class="col-lg-2 col-sm-4">
                        {% if u.profile_img %}
                        <img class="rounded-circle" src="{{ u.profile_img.url}}"
                            style="width: 100px; height: 100px;">
                        {% else %}
                        <img class="rounded-circle" src="{% static 'images/user/default_profile.jpg' %}"
                             alt="Default Profile Image" style="width: 100px; height: 100px;">
                             {% endif %}
        
                      
                    </div>
                   
                    <div class="col-lg-10 col-sm-8 pname pt-5">
                       <p class="h5 text-dark capitalize">{{user.first_name}}</p>
                       <p class="h6 text-secondary">{{user.email}}</p>

                        <!-- <a role="button" class="btn btn-secondary user-btn-delete ms-2 bc_mv"><i
                                class="fa-regular fa-trash-can"></i> Delete</a> -->

                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col-sm-6 mb-2">
                        <label>User Name</label><br>
                        <div class="card custom-cards">
                            <div class="card-body">
                                {{user.username}}
                            </div>
                          </div>
                    </div>
                    <div class="col-sm-6 mb-2">
                        <label>Last Name</label><br>
                        <div class="card custom-cards">
                            <div class="card-body capitalize">
                              {{user.last_name}}
                            </div>
                          </div>
                     
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <label>Department</label><br>
                        <div class="card custom-cards">
                            <div class="card-body">
                               {{u.occupation}}
                            </div>
                          </div>
                    </div>
                    <div class="col-sm-6">
                        
                      




                          <label>Phone Number</label><br>
                          <div class="card custom-cards">
                              <div class="card-body">
                                  {{u.phone_number}}
                              </div>
                            </div>





                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
         
    


        </div>
    </div>
</div>
{% endblock %}

users/templates/profile/user_profile_sidebar.html
<div class="list-group rounded-4">
    <a href="{% url 'user_app:user_profile_list' %}" class="list-group-item list-group-item-action user-profile {% if active == 'general' %} {{'active'}} {% endif %}">General</a>
    <a href="{% url 'user_app:user_profile_edit' %}" class="list-group-item list-group-item-action user-profile {% if active == 'edit_profile' %} {{'active'}} {% endif %}">Edit Profile</a>
    <a href="{% url 'user_app:user_password_change_profile' %}" class="list-group-item list-group-item-action user-profile {% if active == 'profile_change_password' %} {{'active'}} {% endif %}">Password</a>
    <a href="{% url 'user_app:user_courses' %}" class="list-group-item list-group-item-action user-profile {% if active == 'user_courses' %} {{'active'}} {% endif %}">My Courses</a>
    <a href="{% url 'user_app:saved_page' %}" class="list-group-item list-group-item-action user-profile {% if active == 'saved_course' %} {{'active'}} {% endif %}">Saved Courses</a>
    <a href="" class="list-group-item list-group-item-action admin-logout mt-1 rounded-bottom mb-2"
        data-bs-toggle="modal" data-bs-target="#adminlogout">Logout</a>


    <!-- Modal -->

    <div class="modal fade text-center logout-modal" id="adminlogout" tabindex="-1"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog ">
            <div class="modal-content align-items-center">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="exampleModalLabel">Logout?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <div class="modal-body modal-text">
                    Are you sure you want to Logout?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-modal btn btn-outline-dark px-5 mx-auto ms-4"
                        data-bs-dismiss="modal">No, Cancel</button>
                        <form method="post" action="{% url 'user_app:user_logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn-modal btn btn-outline-dark px-5 mx-auto ms-4">Yes, Logout</button>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>